Final changes

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -40,4 +40,21 @@ jobs:
       working-directory: ./rust_extractor
       run: docker build -t rust_extractor .
     
-    # Add deployment steps here if deploying to a cloud service like AWS, Azure, or GCP.
+    - name: Start Docker containers
+      run: |
+        docker-compose up -d
+        sleep 30  # Wait for containers to start
+
+    - name: Check if application is running
+      run: |
+        response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)
+        if [ $response = "200" ]; then
+          echo "Application is running successfully!"
+        else
+          echo "Application failed to start. HTTP response code: $response"
+          exit 1
+        fi
+
+
+    - name: Stop Docker containers
+      run: docker-compose down
